# These are supported funding model platforms

github: [DarkStarStrix]
patreon: # Replace with a single Patreon username
open_collective: # Replace it with a single Open Collective username
ko_fi: # Replace it with a single Kofi username
tidelift: # Replace it with a single Tide lift platform-name/package-name e.g., npm/babel
community_bridge: # Replace it with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace it with a single Libera pay username
issuehunt: # Replace it with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace it with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
