data:
  batch_size: 32
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
logging:
  plot_gradients: true
  plot_learning_rate: true
  tensorboard: true
  verbose: true
model:
  hidden_dim: 128
  input_dim: 10
  output_dim: 5
  type: linear
optimization:
  compile_model: false
  mixed_precision: true
  optimizer: adamw
  scheduler: cosine
  weight_decay: 0.01
training:
  early_stopping: true
  epochs: 10
  gradient_clip_val: 1.0
  learning_rate: 0.001
  model_checkpoint: true
