data:
  batch_size: 32
  num_workers: 4
logging:
  tensorboard: false
model:
  input_dim: 1
  output_dim: 1
  task: regression
  type: linear_regression
optimization:
  optimizer: adam
training:
  accumulate_grad_batches: 2
  batch_size: 16
  epochs: 100
  gradient_clip_val: 0.5
  learning_rate: 0.01
  max_steps: 100
