data:
  augmentation:
    enabled: true
    feature_dropout: 0.1
    noise_std: 0.1
  batch_size: 32
  num_workers: 4
  pin_memory: true
logging:
  log_every_n_steps: 10
  metrics:
  - accuracy
  - precision
  - recall
  - f1_score
  tensorboard: true
model:
  architecture:
    activation: relu
    batch_norm: true
    dropout_rate: 0.3
    num_layers: 3
  hidden_dim: 256
  input_dim: 10
  output_dim: 5
  task: classification
  type: classification
optimization:
  gradient_clip_val: 1.0
  min_lr: 1.0e-06
  mixed_precision: true
  optimizer: adam
  scheduler: one_cycle
  scheduler_config:
    div_factor: 10.0
    final_div_factor: 100.0
    pct_start: 0.3
  weight_decay: 0.01
training:
  batch_size: 32
  class_weights:
  - 1.0
  - 1.2
  - 0.8
  - 1.5
  - 1.3
  early_stopping: true
  epochs: 30
  learning_rate: 0.002
  patience: 7
