data:
  batch_size: 32
  num_workers: 7
  pin_memory: true
logging:
  log_every_n_steps: 10
  metrics:
  - accuracy
  - f1
  tensorboard: true
model:
  input_dim: 10
  output_dim: 32
  task: binary_classification
  type: logistic_regression
optimization:
  gradient_clip_val: 1.0
  min_lr: 1.0e-06
  mixed_precision: true
  optimizer: adam
  scheduler: cosine
  weight_decay: 0.01
training:
  batch_size: 32
  early_stopping: true
  epochs: 50
  learning_rate: 0.01
  patience: 5
