data:
  batch_size: 64
  num_workers: 4
model:
  input_dim: 10
  output_dim: 5
  type: linear
optimization:
  accumulate_grad_batches: 1
  gradient_checkpointing: false
  mixed_precision: false
training:
  early_stopping: true
  epochs: 50
  learning_rate: 0.01
  optimizer: sgd
  scheduler: linear
